### ISSUE TITLE
Is there any solution to this problem I see?

### ISSUE THREAD

**Issue by masshuvo** [Mino260806/MessengerPro#18]
![Screenshot_2023-07-06-19-42-17-418_com facebook orca](https://github.com/Mino260806/MessengerPro/assets/108648096/bb657af3-b12a-408f-9d41-ed0842aaf6b9)
![Screenshot_2023-07-06-19-42-08-589_com miui home](https://github.com/Mino260806/MessengerPro/assets/108648096/afce1004-5ad2-4f80-b69e-5a99ee74e393)

**Comment by Mino260806** [comment]
Yes, wait for next major release, everything will be fixed
