### ISSUE TITLE
Can't access to Messanger Pro Settings

### ISSUE THREAD

**Issue by KaziRifatMorshed** [Mino260806/MessengerPro#2]
I downloaded the messanger app (350.0.0.7.89) from the given link, logged in to my FB acc and then installed the Messanger Pro-0.1.0-Alpha (4.55MB). Installation was successful. When I entered the Messanger app, I found no way to go to MsngerPro Settings. No icon or anything appeared 😔.
Using official Samsung M21(SM-m21f;4/64); One UI Core 3.1 (based on Android 11)

**Comment by Mino260806** [comment]
Do you have LSPosed? Is your phone rooted ?

**Comment by KaziRifatMorshed** [comment]
No, I don't have LSPosed and my device is NOT rooted. And, I do not want to root my device as it will affect my warranty 😔

**Comment by KaziRifatMorshed** [comment]
However, me, as a newcomer, the whole process is not clear 🙃🙃 I think, there should be some documentations with mentioning possible risks and warnings

**Comment by Mino260806** [comment]
Documentation may be added in the future. Sorry for the inconvenience.
