### ISSUE TITLE
GPT Support

### ISSUE THREAD

**Issue by knasiotis** [Mino260806/MessengerPro#20]
add commands for gpt-3 or chat-gpt, this would be amazing, there is an active API for it.
Could even include bing search support

**Comment by Mino260806** [comment]
The API is active but not free, are you willing to pay for it ?

**Comment by knasiotis** [comment]
Ah I didn't know that. Maybe someone adds his own API key in settings?

**Comment by Mino260806** [comment]
I don't think people are willing to pay for it, or are they ?

**Comment by knasiotis** [comment]
> I don't think people are willing to pay for it, or are they ?

that's valid, I guess, I hope we can find many fun APIs. You have done a good work!

**Comment by Mino260806** [comment]
Thanks! If you find any cool API, don't hesitate to open an issue and tell us!
