### ISSUE TITLE
[BUG] Locking a chat with fingerprint makes Messenger crash sometimes

### ISSUE THREAD

**Issue by Sandoiitchisan** [Mino260806/MessengerPro#24]
When I try to enable fingerprint on some chat, it will sometimes make my Messenger app crash, I open it again, enable it and it will work

**Comment by Mino260806** [comment]
Are you on newest messenger version ? I fixed a similar bug, but I'm unsure.

Otherwise I need you to provide logs, or I can't help

**Comment by Sandoiitchisan** [comment]
Nope, lastest version said to be compatible on GitHub with auto update disabled. How can I send logs ?

**Comment by Sandoiitchisan** [comment]
I meant last compatible version as the app told me when I opened Messenger, my bad

**Comment by Mino260806** [comment]
I'm waiting for logs, google it

**Comment by Sandoiitchisan** [comment]
Can't use logcat command in ADB for now, my USB cable just died yesterday
evening, but when I got a new one, I may update the issue

**Comment by Mino260806** [comment]
You can use wireless adb, google it

**Comment by Sandoiitchisan** [comment]
That's right I'll do this
