### ISSUE TITLE
App keeps crashing once LPosed Module is hooked

### ISSUE THREAD

**Issue by HarriBuh** [Mino260806/MessengerPro#26]
G Pixel 7
Android 13
Rooted with HuskyDH's Magisk 25.2

Steps to reproduce:

1. Installed the custom version "messenger416-pie-noroot.apk"

2. Logged in and then force-closed it

3a. Installed "mpro.apk", enabled it in LPosed, rebooted device
3b. Installed "mpro.apk", enabled it in LPosed, did not reboot device

4. Opened Messenger app

5. Got some welcoming pop-up from the MPro App

6. App crashes immediately after this

7. Loop of 5. everytime I reopen the app
x force-closing doesn't help
x force-closing + deleting cache doesn't help

**Comment by Mino260806** [comment]
Did you read installation instructions ?
The root version doesn't have noroot in it's name (messenger-pie.apk). The app is crashing because the module is getting applied twice (one for noroot and one by lsposed)
