### ISSUE TITLE
Remove the pop-up of mismatched version

### ISSUE THREAD

**Issue by tykimikk** [Mino260806/MessengerPro#27]
Or add an option to disable it

**Comment by faroukbmiled** [comment]
For now, you can just recompile the apk with the pop up removed, to do this edit MProPatcher.java (MessengerPro\app\src\main\java\tn\amin\mpro2\MProPatcher.java) by commenting out ```if (gateway.state.getOrcaVersion() > ModuleInfo.MAX_ORCA_VERSION)``` in ensureCompatibility line 107

**Comment by Mino260806** [comment]
Resolved with PR #61
