### ISSUE TITLE
Mod doesn't work with cloning apps.

### ISSUE THREAD

**Issue by karelo911** [Mino260806/MessengerPro#28]
I use a third-party app (DualSpace) so I can use two messenger accounts simultaneously (one for work and one for personal use). However, I can't seem to clone the modded apk designed to work with messenger pro (messenger416-pie-noroot.apk). It only leaves a black screen when I use it with such apps. I tried using the official messenger apk and it works just fine. What could be the solution to this? Thank you so much.

**Comment by Mino260806** [comment]
I don't know exactly how the hook is applied internally
You right place to post this issue is here https://github.com/NeonOrbit/MRVPatchManager
