### ISSUE TITLE
Tasker plugin actions do not work if messenger is not open

### ISSUE THREAD

**Issue by rollingmoai** [Mino260806/MessengerPro#30]
I have created a simple flow using [Automate](https://llamalab.com/automate/) to send a message at a specific time. However, the plugin does not work when the app is not open or the screen is locked. Any help on how to make this work?

**Comment by Mino260806** [comment]
It works for me, I made a task that sends a message every hour at night and it worked perfectly at the exact time.

I observed some noticeable delays though when battery optimizations is on in messenger. Can you disable it and test again ?

dontkillmyapp.com

**Comment by icewyvrn** [comment]
@Mino260806 what's your android version? i have lineageos android 13, and i have the same problem.
