### ISSUE TITLE
Can't install facebook app after installing MessengerPro

### ISSUE THREAD

**Issue by SarkarKurdish** [Mino260806/MessengerPro#31]
I've uninstalled the facebook app so I can install the MPRO as the Readme suggests after that the Faceook app cannot be installed, whe n installing the facebook app this error will show up (app not installed as package conflicts with an existing package)

I've tried to install cloned facebook app, The apps were not installed tho I don't think it's related to MPRO

Device Used:
Redmi Note 9 Pro - MIUI 14.0.3
Redmi Note 10 Pro

**Comment by Mino260806** [comment]
It will be solved in next release

**Comment by SarkarKurdish** [comment]
Eta?
