### ISSUE TITLE
Does not work either way

### ISSUE THREAD

**Issue by sfoklus** [Mino260806/MessengerPro#32]
Whether I have navigation gestures turned on or off, it doesn't work.
If I have them on then it's impossible for the modules menu to be presented.
If I have navigation buttons turned on, most of the module settings still don't work. I was forced to go back to 0.2-alpha version for mostly everything to work again. Also will there a way to remove inbox ads in the future?

**Comment by Mino260806** [comment]
Explain "it doesn't work" in details. What did you do to assume it isn't working ?

Did you read https://github.com/Mino260806/MessengerPro/wiki/Usage-Guide ?

**Comment by sfoklus** [comment]
Yes I did. What I mean is that if I have the gesture navigation turned on on my android phone, then presenting the toolbar menu is impossible. But even if I do have them turned off and instead I have the 3 button navigation turned on, then feautres like the commands don't work at all.

**Comment by Mino260806** [comment]
You can configure toolbar in Settings > Toolbar > Summon toolbar and choose direction up or down

**Comment by sfoklus** [comment]
This doesn't show the toolbar but rather the module settings.

**Comment by Mino260806** [comment]
Read [usage guide](https://github.com/Mino260806/MessengerPro/wiki/Usage-Guide)

**Comment by nnoc** [comment]
I confirm that it does not work for me either.

Turned off gesture navigation:
- Swiping from the right does nothing.
- Long-pressing "Chats" in the conversations list (I assume this is what the home screen mentioned is) does nothing.

Messenger
com.facebook.orca
Version: 416.0.0.9.76

LSPosed 1.8.6 (6712) - Zygisk
Rooted Google Pixel 5 Android 13 TQ3A.230605.011

**Comment by nnoc** [comment]
@Mino260806
Do you have some idea of what I can try to debug this?

**Comment by cr4sh-me** [comment]
Same. I can't open settings of messenger pro, even using right messenger version

**Comment by Mino260806** [comment]
> * Swiping from the right does nothing.
> * Long-pressing "Chats" in the conversations list (I assume this is what the home screen mentioned is) does nothing.

Are you sure the mod is working ? Did you get a welcome dialog when you first launched messenger after enabling it ?
