### ISSUE TITLE
Messenger ADS & Hide Mpro icon from launcher

### ISSUE THREAD

**Issue by bahaedin** [Mino260806/MessengerPro#45]
Great work bro , i have a suggestion for you !
Can you merge revanced patches with your mods to get rid o this annoying ADS ?

![IMG_20230920_091600](https://github.com/Mino260806/MessengerPro/assets/57917164/95f7cdfd-ba86-4299-bf27-57dfa170b715)

And another one is to hide mpro icon from launcher It's no use  !!

![Screenshot_20230920-092311_Paranoid_Launcher](https://github.com/Mino260806/MessengerPro/assets/57917164/09e1248c-bcd5-4b53-a0a8-1fbad01d4d8d)

**Comment by Joeeeeb5** [comment]
+1 on the ads

**Comment by Mino260806** [comment]
Unless someone states a convincing reason, ads will not be removed as stated in #8
