### ISSUE TITLE
Duplicate option for hiding the seen indicator

### ISSUE THREAD

**Issue by Joeeeeb5** [Mino260806/MessengerPro#46]
There are 2 switches for hiding the seen indicator, one in toolbar settings called "hide MESSAGE seen indicator" and one in features called "hide CONVERSATION seen indicator". I don't get the difference between them. Also, toggling the switch from the toolbar controls the conversation one. It would be much less confusing if they were unified as one option and hid the indicator everywhere

**Comment by Mino260806** [comment]
There's no difference
