### ISSUE TITLE
Hide "Marketplace" folder from chat list

### ISSUE THREAD

**Issue by pragyanone** [Mino260806/MessengerPro#54]
I would like to request a feature to be able to hide (/archive) the Marketplace folder from the chat list. Please refer to the screenshot attached.
And, thank you for the awesome app.
![HideMarketplaceFolderFromChatList](https://github.com/Mino260806/MessengerPro/assets/59058629/c6d381ce-fb88-4eb2-bdf6-c1d814d45b3b)

**Comment by Mino260806** [comment]
I never had this folder so I don't know how I can remove it because I can't test it on my phone. Besides this seems somehow related to ads, and I don't want to take a step in this field as explained in #8.
