### ISSUE TITLE
Issue: Facebook/Fb Lite Unable to Download/Install When Using MessengerPro

### ISSUE THREAD

**Issue by 1NS1GN1USPH** [Mino260806/MessengerPro#56]
Greetings. This is not necessarily an issue, but it can be for people like me who not only use your mod, but also uses Facebook / Fb Lite itself. When using the app and trying to download and install both Facebook and FB Lite {please, don't ask why}, they won't download as there's a "conflicting package" {that being messenger pro itself}. Can you please fix this ASAP or let us have a download link of both FB and FB Lite that would work well with messenger pro and have no issues installing/using whatsoever? Thank you if so {P.S.: Reply to this issue board if you can actually fix this issue or not, Ty.}

**Comment by Mino260806** [comment]
Thanks for taking the time to report. The problem has been already raised here #37. Read [this comment](https://github.com/Mino260806/MessengerPro/issues/37#issuecomment-1795336799)
