### ISSUE TITLE
Show "querying response" as a toast or give a short vibration as feedback 

### ISSUE THREAD

**Issue by Joeeeeb5** [Mino260806/MessengerPro#58]
I don't know how to make an issue on Loukious's fork so I wrote it here

**Comment by Joeeeeb5** [comment]
Another one, i keep getting randomly signed out and the messenger app crashes

**Comment by Mino260806** [comment]
> I don't know how to make an issue on Loukious's fork so I wrote it here
What's "Loukious's fork" if I'm allowed to ask ? 

> Another one, i keep getting randomly signed out and the messenger app crashes
Please open a seperate issue

> Show "querying response" as a toast or give a short vibration as feedback
The blocking dialog is intentional, because it prevents the user from leaving the conversation as it may lead to crashes and other unpredictable consequences. I'm sorry but I cannot fulfill your suggestion

**Comment by Joeeeeb5** [comment]
Loukious's made a fork of this repository and added more features, like the urban dictionary api support, material u colours etc

**Comment by rollingmoai** [comment]
@Loukious Can you open the issues tab on your repo since it is closed? Thanks!
