### ISSUE TITLE
Enhancement: Hide "Active-bar"

### ISSUE THREAD

**Issue by lezsakdomi** [Mino260806/MessengerPro#6]
Hi!

Thank you for the awesome app!

In Messenger above the recent messages there's a bar which showcases currently online people:

![Screenshot_20220402-073143_Messenger](https://user-images.githubusercontent.com/8544161/161368187-f0f7fdd4-a1e5-48a7-a8d4-fe9135f4d421.png)

(I've censored it's contents)

It's seemingly random, and always moves my attention there with it's animations.

This bar makes me annoyed a lot, and I'd be really happy if you could get rid of it. This feature has to reside behind an inactive switch in setting turned off by default, because some people might rely on this feature.

Unfortunately I'm not really into Xposed development, I hope it's not too difficult.

Thanks in advance, I hope this issue would get to a release.

**Comment by Mino260806** [comment]
Thanks for the suggestion.

**Comment by alexhulbert** [comment]
I'd really like to see this feature as well

**Comment by Mino260806** [comment]
Not feasable
> any UI related features are no longer supported, because UI elements are heavily obfuscated and frequently changed by meta, so thery are impossible to keep track of.

Sorry.
