### ISSUE TITLE
Messenger Crashes

### ISSUE THREAD

**Issue by MohamadBayz** [Mino260806/MessengerPro#9]
I used the module for about ~3 weeks it was working fine, until i made a video call with a friend then the app started crashing now, I can't even open it whenever, I open it it crashes.

**Comment by igorkietrz** [comment]
You found a fix?

**Comment by MohamadBayz** [comment]
Yes i uninstalled my messenger and installed this version that's mentioned in the redme
https://www.apkmirror.com/apk/facebook-2/messenger/messenger-350-0-0-7-89-release/facebook-messenger-350-0-0-7-89-android-apk-download/
